---
name: lint
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
  workflow_dispatch:
  workflow_call: # so composite actions can use this

permissions:
  pull-requests: read
  contents: read
  checks: write
jobs:
  lint:
    uses: delineaxpm/github-workflows/.github/workflows/lint.yml@main
    secrets: inherit
