---
name: release
on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@777394c89f8ed6fcf1649505277c46c1cd06494d # v4
        with:
          go-version-file: go.mod
      # https://github.com/magnetikonline/action-golang-
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # tag=v2.0.2
        with:
          aqua_version: v2.21.3
          enable_aqua_install: true
          aqua_opts: '--tags release'
        env:
          AQUA_LOG_LEVEL: debug
          AQUA_OPTS: ''
      - name: mage-tidy
        uses: magefile/mage-action@6a5dcb5fe61f43d7c08a98bc3cf9bc63c308c08e # v3
        with:
          version: latest
          args: init
      - name: docker-login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ secrets.DSV_DOCKER_USERNAME }}
          password: ${{ secrets.DSV_DOCKER_PASSWORD }}
      - name: mage-release
        uses: magefile/mage-action@6a5dcb5fe61f43d7c08a98bc3cf9bc63c308c08e # v3
        with:
          version: latest
          args: release
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
          DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # renovate: tag=v3.1.0
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     # GitHub sets this automatically
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
      #     SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
      #     DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}
